# CI for the src folder
name: CI

on:
  pull_request:
    branches:
      - master
      - next
    paths:
      - 'test/**'
      - 'src/**'
      - 'config/**'
      - 'ci-bin/**'
      - 'ci-bin/*'
      - 'package.json'
      - 'package-lock.json'
      - 'Dockerfile'
  push:
    branches:
      - master
      - next
    paths:
      - 'test/**'
      - 'src/**'
      - 'config/**'
      - 'ci-bin/**'
      - '.github/**'
      - 'package.json'
      - 'package-lock.json'
      - 'Dockerfile'

jobs:
  test-bitsocial-cli:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Smoke test Docker deps stage
        run: docker build --target deps -t bitsocial-cli:deps-smoke .

      - run: npm ci
      - run: npm run build
      - run: npx oclif manifest

      # disable hosts we shouldn't use
      - run: sudo echo "255.255.255.255 cloudflare-ipfs.com" | sudo tee -a /etc/hosts
      - run: sudo echo "255.255.255.255 pubsubprovider.xyz" | sudo tee -a /etc/hosts

      - run: DEBUG="bitsocial*, plebbit*, oclif*" npm run test:cli
